name: Update Shadowrocket Rules

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    
    # --- 新增内容 ---
    # 授予 Action 写入仓库内容的权限
    permissions:
      contents: write
    # --- 新增内容结束 ---

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run rule update script
        run: python update_rules.py

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Auto-update Shadowrocket rules"
          file_pattern: ultimate_edition.conf
